### PR TITLE
Links proposals

### PR DESCRIPTION
**Pull request by sbesson**
### Context

In addition to the definition of Formats & API per functional components, we need to define and represent the links between the components.

cmsolinks

## Proposal

This PR includes a couple of suggestions for this link representation. The first representation is implicit and based on file/folder naming conventions while the second representation proposes to store these links explicitly using OME Annotations. See the Readme for a more complete description.

As discussed with @joshmoore @pcmasuzzo , both representations are not mutually exclusive and could potentially correspond to various levels of requirements e.g. minimal requirements/recommendations for implicit linking vs repository submission requirements for explicit linking.

### CODE REVIEW

**Comment by simleo** [comment]
See https://gist.github.com/simleo/8bf7353e57055aa2b745885d00a35fc4 based upon this PR and https://github.com/simleo/ome-files-py/commit/020f5b5955b723e14fd7f57309562fd5af4e9024

**Comment by simleo** [comment]
I think the best solution is the one that uses MapAnnotations, whose value is already structured in the OME model. Since XMLAnnotations contain arbitrary XML instead, we would need to create a custom schema for that, and that would basically amount to reinventing the wheel if the key/value pairs already provided by MapAnnotations are sufficient for our purposes (and it looks like they are).

Instead of using the same key (`FilePath` in the example) for all linked files, we might want to simplify the reader's job by using different keys for each, something like `DataPackagePath` and `ISAPath`.

**Comment by sbesson** [comment]
Thanks @simleo for the input. I am also inclined to focus on MapAnnotation for this round - we can always refine/revisit this policy in the future. With regard to this PR, is it worth keeping the other examples (implicit, XMLAnnotations) or should I remove them from this branch in favor of the MapAnnotation only and only mention them in the Readme?

**Comment by pcmasuzzo** [comment]
I also believe the `MapAnnotation `would do more than fine for now (though I am no expert in the OME model).

@sbesson - perhaps would make more sense to 'move' the other examples (not sure where though), and leave the `MapAnnotation` one in this PR.
Alternatively, another PR with _only_ the `MapAnnotation`?

**Comment by sbesson** [comment]
If we want to preserve them, happy to move them to an additional directory e.g. `links/{legacy,investigation}/`. Alternatively, removing them would still preserve them in the Git history of the repo and this PR would document the rationale/decision making.

**Comment by pcmasuzzo** [comment]
They will be in the Git history indeed, so feel free to remove them. Most likely we won't be go back to them anymore, but if we will have to - good to have them.

**Comment by sbesson** [comment]
@pcmasuzzo @simleo: updated this PR with the chosen proposal for links. Can I leave you to have a final sign-off and we should be able to merge this as a starting template? We can review/implement the suggestions in https://github.com/CellMigStandOrg/CMSO-Samples/pull/10#issuecomment-288138412 as we start deriving concrete examples based on the initial sample.

**Pull request merged**
